backend:
    name: git-gateway
    branch: master

media_folder: "_site/media/uploads"
public_folder: "/media/uploads"

collections:
  - name: "everything"
    label: "Everything"
    folder: "e"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "/layouts/e.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date",
          name: "date",
          widget: "datetime",
          default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }