backend:
    name: git-gateway
    branch: master

media_folder: "_site/media"
public_folder: "/media"

collections:
  - name: "everything"
    label: "Everything"
    folder: "e"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/e.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }